name: Run JMeter Tests

on:
  push:
    branches:
      - main  # Adjust if you want it to run on other branches or events (like pull_request)

jobs:
  run-jmeter-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the GitHub repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JMeter on the runner
      - name: Install JMeter
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jre
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.5.tgz
          tar -xvzf apache-jmeter-5.5.tgz
          sudo mv apache-jmeter-5.5 /opt/jmeter
          sudo ln -s /opt/jmeter/bin/jmeter /usr/local/bin/jmeter

      # Step 3: Run JMeter test plan
      - name: Run JMeter test
        run: |
          jmeter -n -t jmeter/weather_test_plan.jmx -l result.jtl

      # Step 4: Upload the results
      - name: Upload JMeter results
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-results
          path: result.jtl

      - name: Generate JMeter HTML Report
        run: |
          /opt/jmeter/bin/jmeter -g result.jtl -o /tmp/jmeter-report
      - name: Upload JMeter HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-html-report
          path: /tmp/jmeter-report
